name: sruzy
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1
  url_launcher: "^3.0.2"
  flappy_search_bar: 1.4.1
  custom_navigator: ^0.2.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.3
  json_serializable: ^3.2.5

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/Nunito.ttf